import React from 'react';
export default class HoutaiCenter extends React.Component {
    constructor(props){
        super(props);
        this.state = {
            
        }
    };
    render(){
        return(
            <div>我是后台中心
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
                <div>我是后台中心</div>
            </div>
        )
    }
}